// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2lHpCJeUbAhC1lYlXFGODWpWTBe7O60',
    appId: '1:97899051501:web:d93779c62bbdbe6a474fe4',
    messagingSenderId: '97899051501',
    projectId: 'fir-auth-demo-187af',
    authDomain: 'fir-auth-demo-187af.firebaseapp.com',
    storageBucket: 'fir-auth-demo-187af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvkc1nlvH5GK4JOSNoBP2NaU5atYc1U04',
    appId: '1:97899051501:android:98472117af352c8c474fe4',
    messagingSenderId: '97899051501',
    projectId: 'fir-auth-demo-187af',
    storageBucket: 'fir-auth-demo-187af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6n19JhY78iQwZlYEYuDW6rXP1RYn01-Y',
    appId: '1:97899051501:ios:b774d9dd0eb16774474fe4',
    messagingSenderId: '97899051501',
    projectId: 'fir-auth-demo-187af',
    storageBucket: 'fir-auth-demo-187af.appspot.com',
    iosClientId: '97899051501-c9fbgrqjn1n9df66b1dnqncpj5uh8n4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6n19JhY78iQwZlYEYuDW6rXP1RYn01-Y',
    appId: '1:97899051501:ios:b774d9dd0eb16774474fe4',
    messagingSenderId: '97899051501',
    projectId: 'fir-auth-demo-187af',
    storageBucket: 'fir-auth-demo-187af.appspot.com',
    iosClientId: '97899051501-c9fbgrqjn1n9df66b1dnqncpj5uh8n4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
